name: Build Windows (WPF)

on:
  push:
    branches: [development]

jobs:
  build:   
    runs-on: windows-latest

    env:
      Solution_Name: XACTAS.sln
      Project_Path: XACTAS.WPF/XACTAS.WPF.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      
    - name: Build WPF Project
      run: dotnet build ${{ env.Project_Path }}